# consult: https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/add-or-copy
# Forked: https://hub.docker.com/r/amancevice/pandas
FROM		phirov/scipy:3
MAINTAINER	phirov@163.com

RUN		pip3 install jmespath pymongo
